spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commande
    username: isi
    password: isi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: commandeConfirmation:com.isi.commande.kafka.CommandeConfirmation

server:
  port: 8070
application:
  config:
    client-url: http://localhost:8222/api/v1/clients
    payement-url: http://localhost:8222/api/v1/payements
    produit-url: http://localhost:8222/api/v1/produits
