spring:
  data:
    mongodb:
      username: isi
      password: isi
      host: localhost
      port: 27017
      database: client
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payementGroup,commandeGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: commandeConfirmation:com.isi.notification.kafka.commande.CommandeConfirmation,payementConfirmation:com.isi.notification.kafka.payement.PayementConfirmation

  mail:
    host: localhost
    port: 1025
    username: isi
    password: isi
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
