-- INSERT INTO categorie (id, nom, description) VALUES
--                                                  (nextval('categorie_seq'), 'Computers', 'Computers KeyBoard'),
--                                                  (nextval('categorie_seq'), 'Electronics', 'Various Electronic Items'),
--                                                  (nextval('categorie_seq'), 'Furniture', 'Home and Office Furniture'),
--                                                  (nextval('categorie_seq'), 'Books', 'Books of various genres'),
--                                                  (nextval('categorie_seq'), 'Clothing', 'Men and Women Clothing'),
--                                                  (nextval('categorie_seq'), 'Toys', 'Children Toys'),
--                                                  (nextval('categorie_seq'), 'Food', 'Groceries and Food Items'),
--                                                  (nextval('categorie_seq'), 'Beauty', 'Beauty and Personal Care'),
--                                                  (nextval('categorie_seq'), 'Sports', 'Sports Equipment'),
--                                                  (nextval('categorie_seq'), 'Automotive', 'Automotive Parts and Accessories');
--
--
-- INSERT INTO public.produit (id, nom, description, quantite, prix, categorie_id) VALUES
--
--                                                                                     (nextval('produit_seq'), 'HP Laptop', 'High performance laptop', 15, 300000,),
--                                                                                     (nextval('produit_seq'), 'Office Chair', 'Ergonomic office chair', 30, 50000, 3),
--                                                                                     (nextval('produit_seq'), 'Mystery Novel', 'Suspense and thriller book', 50, 2000, 4),
--                                                                                     (nextval('produit_seq'), 'Jeans', 'Comfortable denim jeans', 40, 3000, 5),
--                                                                                     (nextval('produit_seq'), 'Lego Set', 'Building blocks toy', 25, 8000, 6),
--                                                                                     (nextval('produit_seq'), 'Olive Oil', 'Extra virgin olive oil', 60, 500, 7),
--                                                                                     (nextval('produit_seq'), 'Shampoo', 'Herbal essence shampoo', 45, 150, 8),
--                                                                                     (nextval('produit_seq'), 'Basketball', 'Official size basketball', 35, 1200, 9),
--                                                                                     (nextval('produit_seq'), 'Car Tire', 'All-season car tire', 10, 50000, 10),
--                                                                                     (nextval('produit_seq'), 'Apple iPhone 12', 'Apple smartphone', 25, 200000, 2),
--                                                                                     (nextval('produit_seq'), 'Dell Monitor', '24 inch LED monitor', 20, 70000, 1),
--                                                                                     (nextval('produit_seq'), 'Dining Table', 'Wooden dining table', 10, 80000, 3),
--                                                                                     (nextval('produit_seq'), 'Science Fiction Novel', 'Space exploration book', 40, 2500, 4),
--                                                                                     (nextval('produit_seq'), 'T-Shirt', 'Cotton T-shirt', 50, 1500, 5),
--                                                                                     (nextval('produit_seq'), 'Barbie Doll', 'Fashion doll', 30, 6000, 6),
--                                                                                     (nextval('produit_seq'), 'Almonds', 'Raw almonds', 20, 1000, 7),
--                                                                                     (nextval('produit_seq'), 'Face Cream', 'Moisturizing face cream', 60, 200, 8),
--                                                                                     (nextval('produit_seq'), 'Football', 'Professional football', 30, 1300, 9),
--                                                                                     (nextval('produit_seq'), 'Bike Helmet', 'Safety helmet for biking', 20, 20000, 10),
--                                                                                     (nextval('produit_seq'), 'Google Pixel 5', 'Google smartphone', 10, 180000, 2),
--                                                                                     (nextval('produit_seq'), 'Logitech Mouse', 'Wireless mouse', 25, 4000, 1),
--                                                                                     (nextval('produit_seq'), 'Bookshelf', 'Wooden bookshelf', 15, 60000, 3),
--                                                                                     (nextval('produit_seq'), 'Historical Novel', 'Historical fiction book', 35, 2200, 4),
--                                                                                     (nextval('produit_seq'), 'Sweater', 'Woolen sweater', 40, 4000, 5),
--                                                                                     (nextval('produit_seq'), 'RC Car', 'Remote control car', 20, 9000, 6),
--                                                                                     (nextval('produit_seq'), 'Coffee', 'Ground coffee', 50, 1200, 7),
--                                                                                     (nextval('produit_seq'), 'Lipstick', 'Matte finish lipstick', 30, 250, 8),
--                                                                                     (nextval('produit_seq'), 'Tennis Racket', 'Professional tennis racket', 15, 7000, 9),
--                                                                                     (nextval('produit_seq'), 'Car Battery', '12V car battery', 10, 60000, 10);
--
--
